---
version: "3.7"

services:
  protoc:
    build:
      context: ./containers/protoc
    working_dir: /usr/local/src/lab
    volumes:
      - ./:/usr/local/src/lab:cached

  emscripten:
    build:
      context: ./cc/emscripten
    working_dir: /usr/local/src/lab
    volumes:
      - ./:/usr/local/src/lab:cached

  grpc-web-envoy:
    image: envoyproxy/envoy:v1.12.0
    ports:
      - ${GRPC_WEB_ENVOY_PORT}:10000
    volumes:
      - ./grpc-web/envoy.yaml:/etc/envoy/envoy.yaml

  grpc-web-server:
    image: golang:1.13.3-alpine3.10
    ports:
      - ${GRPC_WEB_SERVER_PORT}:9000
    volumes:
      - ./:/usr/local/src/workspace
    working_dir: /usr/local/src/workspace/
    command: go run ./grpc-web/server

  elasticsearch:
    image: elasticsearch:7.3.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - ${ELASTICSEARCH_PORT}:9200

  envoy-filter-example:
    image: envoyproxy/envoy:v1.12.0
    volumes:
      - ./bin/envoy-filter-example:/usr/local/bin/envoy
      - ./envoy/filter/example/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - ${ENVOY_FILTER_EXAMPLE_PORT}:10000

  envoy-filter-hello:
    image: envoyproxy/envoy:v1.12.0
    volumes:
      - ./bin/envoy-filter-hello:/usr/local/bin/envoy
      - ./envoy/filter/example/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - ${ENVOY_FILTER_HELLO_PORT}:10000

  envoy-filter-wasm:
    image: envoyproxy/envoy:v1.12.0
    volumes:
      - ./bin/envoy-wasm:/usr/local/bin/envoy
      - ./envoy/filter/wasm/envoy.yaml:/etc/envoy/envoy.yaml
      - ./_third_party/envoy-wasm/examples/wasm/envoy_filter_http_wasm_example.wasm:/etc/envoy/filter.wasm
    ports:
      - ${ENVOY_FILTER_WASM_PORT}:10000

  envoy-upstream:
    build:
      context: ./envoy/upstream
    ports:
      - ${ENVOY_UPSTREAM_PORT}:8080

  envoy-builder:
    build:
      context: ./containers/envoy-builder
    working_dir: /usr/local/src/workspace/
    volumes:
      - ./:/usr/local/src/workspace:cached
      - ${HOME}/.config/gcloud/application_default_credentials.json:/etc/google_application_default_credentials.json
