---
apiVersion: v1
kind: Namespace
metadata:
  name: grpcserver2
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Pod
metadata:
  name: grpcserver2
  namespace: grpcserver2
  labels:
    app: grpcserver2
    authority-jwt: enabled
spec:
  containers:
    - name: grpcserver2
      image: grpcserver2
---
apiVersion: v1
kind: Service
metadata:
  name: grpcserver2
  namespace: grpcserver2
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: grpcserver2
