---
apiVersion: v1
kind: Service
metadata:
  name: authority
  namespace: authority
spec:
  type: ClusterIP
  selector:
    app: authority
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  sessionAffinity: None
