[package]
name = "wasm-rust"
version = "0.1.0"
authors = ["Yuki Ito <mrno110y@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
log = "0.4.11"
proxy-wasm = "0.1.2"
jsonwebtoken = "7.2.0"
serde = {version = "1.0", features = ["derive"]}
