---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grpcserver2
  name: grpcserver2
  namespace: grpcserver2
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: grpcserver2
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: grpcserver2
    spec:
      containers:
        - image: ghcr.io/110y/lab/grpcserver2:latest
          imagePullPolicy: Never
          name: grpcserver2
          ports:
            - containerPort: 9000
              name: grpc
              protocol: TCP
          env:
            - name: FOO
              value: 'FOO'
