---
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: default
  namespace: grpcserver2
spec:
  origins:
    - jwt:
        issuer: "authority.authority.svc.cluster.local"
        jwksUri: "http://authority.authority.svc.cluster.local:8080/jwks"
